# Jekyll 必须配置
theme: jekyll-theme-minimal
plugins: [jekyll-optional-front-matter]

# 路径配置 (核心修复项)
baseurl: "/ros2"      # 必须与仓库名一致
url: "https://ffff349.github.io"
permalink: pretty

# 主题导航配置（示例）
navigation:
  - text: 主页
    url: /
  - text: 关于
    url: /about/